services:
  - type: web
    name: whatsapp-bot
    runtime: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node whatsapp_sender_clean.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
    autoDeploy: true